
name: 'poc2v3'
version: '1.0.0'

profile: 'poc2v3'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"



models:
  poc2v3:
    +materialized: dynamic_table
    +on_configuration_change: apply 

  
    