name: Sync Snowflake on push

on:
  push:
    branches: [ "main" ]

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Install SnowSQL
        run: sudo apt-get install -y snowflake-snowsql

      - name: Run FETCH in Snowflake
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASS: ${{ secrets.SNOWFLAKE_PASS }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        run: |
          snowsql -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -p $SNOWFLAKE_PASS \
            -q "ALTER GIT REPOSITORY poc2v2.poc2_schema.snowflake_extensions FETCH;"