name: Connect to Snowflake on Push

on:
  push:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  push-to-snowflake:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: myco_git_admin
      SNOWFLAKE_DATABASE: poc2v2
      SNOWFLAKE_SCHEMA: poc2_schema

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Snowflake CLI
        uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"

      - name: Trigger Git Fetch in Snowflake
        run: |
          snow sql -q "ALTER GIT REPOSITORY snowflake_extensions FETCH;"